version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis/redis.conf:/etc/redis/redis_default.conf
      - ./redis/data/:/data
    environment:
      TZ: "Asia/Shanghai"
    command: redis-server /etc/redis/redis_default.conf --appendonly yes
  wvp:
    image: jarvan12th/wvp_pro:v2.0
    restart: always
    ports:
      - "5060:5060"
      - "5060:5060/udp"
      - "18080:18080"
      - "80:80"
      - "10000:10000/tcp"
      - "10000:10000/udp"
      - "30000-30002:30000-30002/tcp"
      - "30000-30002:30000-30002/udp"
    volumes:
      - ./video:/opt/media/www/record/
      - ./logs/wvp:/opt/wvp/logs/
      - ./logs/assist:/opt/assist/logs/
      - ./logs/media:/opt/media/log/
    environment:
      TZ: "Asia/Shanghai"
      # [必须修改] 本机的IP
      WVP_HOST: 0.0.0.0
      WVP_PWD: admin123
      WVP_DOMAIN: 6101130049
      WVP_ID: 61011300490000000001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 6
      REDIS_PWD: root
      ASSIST_JVM_CONFIG: -Xms128m -Xmx256m
      WVP_JVM_CONFIG: -Xms128m -Xmx256m
      ASSIST_CONFIG:
      WVP_CONFIG:
    depends_on:
      - redis
